### ISSUE TITLE
[Wheres My Items] Two bugs - Infinite loop lock and Gui not visible

### ISSUE THREAD

**Issue by SoraHjort** [f4iTh/StardewValleyModding#3]
```
[game] An error occurred in the base update loop: NullReferenceException: Object reference not set to an instance of an object.
   at WheresMyItems.Common.Menus.ItemSearchMenu.<GetItemsMatchingTextboxText>b__14_0(Item item) in C:\Users\f4iTh\development\StardewValleyModding\WheresMyItems\Common\Menus\ItemSearchMenu.cs:line 212
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at WheresMyItems.Common.Menus.ItemSearchMenu.HandleSearchItems(Boolean exitingMenu) in C:\Users\f4iTh\development\StardewValleyModding\WheresMyItems\Common\Menus\ItemSearchMenu.cs:line 195
   at WheresMyItems.Common.Menus.ItemSearchMenu.TextBoxEnter(TextBox sender) in C:\Users\f4iTh\development\StardewValleyModding\WheresMyItems\Common\Menus\ItemSearchMenu.cs:line 220
   at StardewValley.Menus.TextBox.RecieveCommandInput(Char command) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Menus\TextBox.cs:line 290
   at StardewValley.KeyboardDispatcher.Poll() in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\KeyboardSubscriber.cs:line 250
   at StardewValley.Game1._update(GameTime gameTime) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 3499
   at StardewValley.Game1.Update(GameTime gameTime) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 3199
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in SMAPI\Framework\SCore.cs:line 1082
```
^ This is being spammed in the console many times a second

Appears both have been reported several years ago as well on Nexus, with less details. https://www.nexusmods.com/stardewvalley/mods/2086?tab=bugs
(I have not tested the third/oldest bug on there to see if it is still an issue. But the other two are the subject matter of this submitted issue)

Basically, after opening up the search, which appears off screen as well, while you can type into the search box which you can't really see but the top, it locks the game up. And looking at the error, it appears to be trying to find files that doesn't exist unless you're the dev, as evident of looking for things in the "f4iTh" user profile which doesn't exist for users.

Specific Notes: 

[Zoom]
It looks fine on 100% zoom but if you zoom out it will head out of the window. And vice versa if you zoom in.

![image](https://github.com/f4iTh/StardewValleyModding/assets/18604504/43c2dae7-0911-4b2e-9082-3a9ede3a46b3)
![image](https://github.com/f4iTh/StardewValleyModding/assets/18604504/98b657a1-c63e-4a26-989d-c00fed6cedcc)

Also, if the zoom isn't at 100%, the text input box jumps positions while typing.

[Error Message + Infinite Loop of Death]
The error shared at the top is shown every time you type a letter followed with a `[game] WARNING: Mismatched UI Mode Push/Pop counts. Correcting.` message as well. You can still close the text box at this point.

The death loop occurs when you type something in and then press enter.

What's annoying is that this happened on the first green rain day, meaning I'm gonna have to do it again... right after the green tint really did a stress number on my eyes already.

Bonus Bug Round: 

Escape doesn't close it if there is text typed in the box.

**Comment by f4iTh** [comment]
Thank you for the report, and sorry that you’ve had a bad experience using one of my mods.

These issues will be fixed in the next release of the mod. 

I’m unable to replicate the bonus bug, so if that still happens, just let me know.
